server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/doctor_auth_db
    username: root
    password: Anil@5454

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

jwt:
  secret: THIS_IS_A_256_BIT_SECRET_KEY
  expiration: 3600000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
