server:
  port: 8083

spring:
  application:
    name: doctor-service

  datasource:
    url: jdbc:mysql://localhost:3306/doctor_doctor_db
    username: root
    password: Anil@5454

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


