server:
  port: 8083

spring:
  application:
    name: doctor-service

  datasource:
    url: jdbc:mysql://localhost:3306/doctor_doctor_db
    username: root
    password: Anil@5454

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

aws:
  region: ap-south-1
  access-key: AKIAWFW5SMN2JDC7CJ3Z
  secret-key: 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
  s3:
    bucket: my-photo-bucket-108
